### ISSUE TITLE
[Feature Suggestion] Progress on Windows Task Bar

### ISSUE THREAD

**Issue by digocesar** [raspberrypi/rpi-imager#132]
Would be so good when writing a SD card to see the progress on Windows Task Bar. It's common to do other things while writing a SD card but without the task bar progress we need to open the rpi-imager every time to see if it already has finished.
Looking on internet it seems that is possible:
https://www.google.com/search?q=qt+windows+taskbar+progress+bar

**Comment by MagicAndre1981** [comment]
I don't see the progress in Windows 10 with StartIsBack++

![image](https://github.com/user-attachments/assets/773276d8-c8fb-44e4-b517-4428c0f7d4a0)

Do I need to enable this? @maxnet

**Comment by lurch** [comment]
Looks like the feature was removed in https://github.com/raspberrypi/rpi-imager/commit/103924eff0b234e5437e8842a27eba42a47fde64

**Comment by MagicAndre1981** [comment]
ok, thanks.

**Comment by lurch** [comment]
I obviously can't speak directly for @tdewey-rpi (the maintainer of this repo), but it seems unlikely that we'd start using 3rd-party forks of (parts of) Qt.

**Comment by tdewey-rpi** [comment]
@lurch has accurately captured my position. Essentially, using that module introduces a friction point for moving to future Qt releases that is undesirable.

I may decide to implement such functionality directly in Imager, however I very much consider this a "nice-to-have", rather than a hard requirement.
