### ISSUE TITLE
(1.6 on macOS Big Sur) No administrator password to erase SD card

### ISSUE THREAD

**Issue by mjackdk** [raspberrypi/rpi-imager#199]
If I want to write a new image to a SD card, I have to give my administrator password before the process starts.

If I select the "Erase" option, I'm not prompted for my administrator password.

Both actions seems equally destructive.

**Comment by maxnet** [comment]
That is normal.
Mac OS X itself does not ask you for a password either if you format the card with the built-in disk utility, like this:

![Screenshot 2021-03-30 at 21 37 38](https://user-images.githubusercontent.com/1123701/113046666-9bd2a400-91a0-11eb-9b7f-54fc6463e836.png)


The reason the security policies of Mac OS X (and most Linux distributions) do let you format removable media without password, but require that you to enter a password for writing images, is that writing images requires raw disk access.
And such access could theoretically also be used to READ instead of write any data on the disk, bypassing any file ownership and permission restrictions that may be present on computers used by multiple people.
So the password is not to prevent you from doing anything destructive, but to maintain confidently of existing files that may not belong to the user.

**Comment by mjackdk** [comment]
Thank you, that makes sense
