### ISSUE TITLE
rpi-imager-1.62 fails to write to sd card on Mac OS X 11.4

### ISSUE THREAD

**Issue by dcavanau** [raspberrypi/rpi-imager#239]
Used the advanced options to setup SSH, hostname, and WIFI. Writing to a 32 GB SD Card. Selected the Raspberry PI OS Lite (32 bit) option.

Got 'Error creating first run.sh on FAT partition' error message.

**Comment by maxnet** [comment]
Is it a company computer?

One of your co-workers (judging by same company name listed in your github profile) reported this issue being caused by security software used within your organization, and that he was able to get an exception for that.
See for details: https://github.com/raspberrypi/rpi-imager/issues/205

**Comment by dcavanau** [comment]
It isn't a company company computer. I was able to generate an SD card successfully when I didn't do the advance options.

**Comment by maxnet** [comment]
>It isn't a company company computer. I was able to generate an SD card successfully when I didn't do the advance options.

The latter was also the case for the user in the other github issue.
The USB writing restriction the security software imposed did not cover the low level access we are using to write the disk image, to the raw disk device.
It did manage to block the more trivial case of opening a file on a FAT file system for writing, when the destination is an USB device.

**Comment by Arthurus1st** [comment]
Ok, though was common, sorry

**Comment by tdewey-rpi** [comment]
Closing as stale, no responses since '21.
