### ISSUE TITLE
2GB cards not supported, despite imager asking for "at least 2GB"

### ISSUE THREAD

**Issue by dazld** [raspberrypi/rpi-imager#354]
![image](https://user-images.githubusercontent.com/201036/152807337-23c5e9b8-e805-4c3d-b95e-2608cba6a3da.png)

Seems like 1.98GB total capacity isn't being accepted as "at least 2GB".

**Comment by maxnet** [comment]
Suggest you send the card back to where it came from if it is being sold as a 2 GB card, while it is not...


We already go along with the hard drive manufacturer way of calculating things (where a KB is 1000 bytes instead of 1024 bytes).

``
        emit error(tr("Storage capacity is not large enough.<br>Needs to be at least %1 GB.").arg(QString::number(_extrLen/1000000000.0, 'f', 1)));
``

Don't think it is right to round up the number further, to deal with SD card manufacturer's practice to argue that 1.9 GB or even 1.5 GB rounds up to 2 GB as well...

**Comment by dazld** [comment]
I was trying to image a 0.5GB image (32bit lite OS) - I would hope that should be fine even for a 2GB card with lower capacity for whatever reason..?

**Comment by maxnet** [comment]
>I was trying to image a 0.5GB image (32bit lite OS)

0.5 GB is how much data traffic it will cost to download the .zip file.
The image will become larger after uncompression.

**Comment by dazld** [comment]
right - but it's still a 2GB card, and if we disagree on that one, then this report is pointless and I'll save us both time.

**Comment by maxnet** [comment]
It does not have 2.0 GB capacity.
You are missing the .0 GB part in the message.

**Comment by lurch** [comment]
It _might_ work on some "2GB" cards, but that's entirely luck of the draw on whether the card you have is actually big enough or not. Also, I suspect the fact that the image has an uncompressed size of exactly 2.0 GB is probably just coincidence, rather than a deliberate effort to make it small enough to fit on a particular card-size. @XECDesign ?

**Comment by XECDesign** [comment]
> I suspect the fact that the image has an uncompressed size of exactly 2.0 GB is probably just coincidence, rather than a deliberate effort to make it small enough to fit on a particular card-size.

Right, I'm surprised the lite images are still under 2GB. There wouldn't be much room left to play with.

**Comment by lurch** [comment]
"Raspberry Pi OS Superlite" :laughing:
