### ISSUE TITLE
Raspberry pi reported to be 0 bytes size, when it is like 15.5 (16GB)

### ISSUE THREAD

**Issue by Meme-Dealer** [raspberrypi/rpi-imager#628]
![image](https://github.com/raspberrypi/rpi-imager/assets/92324166/55f80e4b-d192-441c-9583-413d77f9d3b0)
I read the size of the raspberry pi, and it is incorrect. How do I get my device to be able to read its size? I have used the rasberry pi imager, which has also failed because of the same reason.

**Comment by maxnet** [comment]
Try "Format as FAT32" in Imager.
If that fails as well, double check "controlled folder access" is disabled.

**Comment by Meme-Dealer** [comment]
> Try "Format as FAT32" in Imager. If that fails as well, double check "controlled folder access" is disabled.

It is off right now, the format as FAT32 was not working because of the error code "failed to allow dasd on device"

**Comment by lurch** [comment]
Maybe a silly question, but are you trying to use a SDHC card in an old card-reader that doesn't support SDHC? (before SDHC, SD cards were limited to 2GB)

**Comment by Meme-Dealer** [comment]
No, I am using a micro sd card in a relatively old card reader

**Comment by Meme-Dealer** [comment]
Also I should add, 16mb was actually the size of my raspberry pi, the micro sd card was 16 gb

**Comment by lurch** [comment]
Yeah, the fact that your screenshot says "MMC/SD USB Device" gave me a hint that it might be a "relatively old card reader", as it has been a long time since I've seen MMC cards mentioned.

micro-SD-card / fullsize-SD-card is just a physical difference, electrically they're the same. So even a micro SD card will be "SDHC" if it's between 4 and 32GB (see https://en.wikipedia.org/wiki/SD_card#Capacity for more info), so if you have an old card reader it **might** not be able to read SD cards / micro SD cards bigger than 2GB.

**Comment by tdewey-rpi** [comment]
@Meme-Dealer Did @lurch's suggestion get you any closer to success?

**Comment by tdewey-rpi** [comment]
Closing as stale - no update since Oct '23.
