### ISSUE TITLE
mmcblk* devices not available "choose storage" (Linux only bug)

### ISSUE THREAD

**Issue by theofficialgman** [raspberrypi/rpi-imager#684]
As the title says, mmcblk* dev nodes appear to be filtered out in the UI of the "choose storage" option.
Most internal device SD card readers (eg: laptop with SD adapter) that have the card reader baked into the SOC expose SD as /dev/mmcblk*

Confirmed on multiple devices with internal SD card readers when booting on some non-SD storage medium:
All using latest published 1.7.5 release
HP Spectre x360 (Ubuntu 23.10)
Jetson Nano 2GB Devkit (Ubuntu 18.04)
Jetson Orin Nano 8GB Devkit (Ubuntu 20.04)
Nintendo Switch (Ubuntu 22.04)

This bug means that I must either:
A: use a separate USB card reader which will expose the device as /dev/sd*
B: use Windows on my laptop to use the internal card reader
C: use a separate software such as Etcher

**Comment by theofficialgman** [comment]
bug reported here as well: https://github.com/raspberrypi/rpi-imager/issues/610 https://github.com/raspberrypi/rpi-imager/issues/606

It is obvious that these drives should be writeable and show up in the GUI. The only drive that should not show up is the current boot drive

**Comment by cillian64** [comment]
My laptop is running Debian 12 and the `/dev/mmcblk0` SD card reader shows up fine and I've written images using it in rpi-imager 1.7.5

![image](https://github.com/raspberrypi/rpi-imager/assets/1373016/104f3e0e-3aea-4cbe-a70d-e2ae583e0b5e)

As discussed on the other tickets, the problem is probably whether or not the devices are marked as hotpluggable/removable.
