### ISSUE TITLE
[BUG] Storage filtering incorrectly removes NVMe targets

### ISSUE THREAD

**Issue by tdewey-rpi** [raspberrypi/rpi-imager#748]
**Describe the bug**
The 'Choose Storage' button presents a window that contains a curated list of storage targets to write OSes to. That curation incorrectly removes NVMe targets on CM4 and other NVMe-capable hardware.

**To Reproduce**
Using Imager v1.8.3:
- Connect NVMe SSD over PCIe
- Open Imager
- Select Raspberry Pi Device, OS, and then select 'Choose Storage'
- Observe no NVMe SSD present in the list

**Expected behaviour**
The NVMe SSD should be present in the list.

**Screenshots or video**
Not required.

**Desktop (please complete the following information):**
Raspberry Pi OS

**The name of the OS you are trying to write**
Not required

**Are you using OS Customisation?**
Not required

**Additional context**
Can be overriden by invoking `rpi-imager` with `--enable-writing-system-drives` as a command line argument

**Comment by lurch** [comment]
Huh, is this a re-occurrence of #158 ?

**Comment by HankB** [comment]
Yes, Looks like the same issue described in #158.

**Comment by maxnet** [comment]
Unable to reproduce on Ubuntu:

![nvm](https://github.com/raspberrypi/rpi-imager/assets/1123701/f2a1a5c7-4d44-4ae8-b5c5-aad9c3773d23)

**Comment by HankB** [comment]
> Unable to reproduce on Ubuntu:

I can confirm that. I installed Ubuntu 23.10 (desktop) on an SD card when when I install and run `rpi-imager` the NVME SSD does appear as a storage target.

The version on Ubuntu 23.10 is `1.7.5+noembed-0ubuntu1 arm64` whereas the version on the 2023-11-28 RpiOS release is `1.8.3`.

**Comment by tdewey-rpi** [comment]
Thanks for the update, @HankB 

This is fairly confusing, then. We've not materially changed the storage filtering mechanism since 1.7.5, so I wouldn't have expected a regression.

So I understand:

1. 1.8.3 is OK on Ubuntu
2. 1.8.3 is NOT OK on Raspberry Pi OS 2023-11-28
3. 1.7.5 is OK on Ubuntu

It sounds suspiciously like the bug is specific to Raspberry Pi OS? In which case, I'll try and find some hardware to reproduce your situation. In the meantime, could you tell me the device name of the NVMe storage in your set-up in Raspberry Pi OS?

**Comment by samlearner-prog** [comment]
Hi - I was trying to use imager on Ubuntu 24.04 to create a raspios 64 image on an NVME drive using imager 1.8.5, and am getting the same issue - the NVME drive is not recognised.

**Comment by HankB** [comment]
You need to differentiate between "not recognized by the OS" vs. "not listed by the imager." There are problems with some SSDs not working with RpiOS. Pimoroni has a list at <https://shop.pimoroni.com/products/nvme-base?variant=41219587178579>. A further note is that just because an SSD worked at one point does not mean it will still work.

Please list the output of `ls -l /dev/nvme*`

**Comment by the-medo** [comment]
Hello, I'm having the same problem on Windows 11.

I'm new to Raspberry, but purchased Pi 5 with Samsung 980 SSD (listed in the link above that it should work). I would like to install ubuntu on it, so I downloaded latest Pi Imager for windows (v1.8.5)

To set it up, I connected SSD to my PC and set it up in bios. Windows can see that disk without a problem and it works, but my "Storage" window in imager is empty. I've tried a lot of stuff - conversions to Basic / Dynamic / GPT disks, with / without volumes, also went to bios and tried to hot-plug it, so now it is like a "removable drive".

I've just quickly checked the code, and PCIe/NVMe isn't listed under recognized bus types:
https://github.com/raspberrypi/rpi-imager/blob/7725ce7a4054371f9152cd0657f071bbbb9bb3ea/src/dependencies/drivelist/src/windows/list.cpp#L322C1-L342C2

Maybe that's why I can't see my SSD?
