### ISSUE TITLE
How to deploy Raspberry pi imager through Intune?

### ISSUE THREAD

**Issue by Saijanjam** [raspberrypi/rpi-imager#783]
Hello Everyone, can someone please help me how to create an raspberry Pi imager application script through powershell app deployment tool kit and how to install via Intune?

Thanks in Advance!!

**Comment by tdewey-rpi** [comment]
Hi @Saijanjam,

Unfortunately this is not a general support forum - the Issues section for the Raspberry Pi Imager project is dedicated to issues directly related to the Raspberry Pi Imager codebase, rather than general crowdsourced support.

As such, I'm going to have to close this as Won't Fix - because there's nothing in this codebase to 'fix' relating to InTune. I'd suggest you use an InTune forum or similar to seek guidance.
