### ISSUE TITLE
[BUG] C++ tr() strings are not translated

### ISSUE THREAD

**Issue by tdewey-rpi** [raspberrypi/rpi-imager#799]
**Describe the bug**
Translated strings in C++ are not translated

**To Reproduce**
1. Install Raspberry Pi Imager v1.8.5
2. Press (CMD + SHIFT + L)
3. Select any non-English language
4. Open 'Choose OS'
5. Scroll to the bottom of the list

**Expected behaviour**
'Erase' and 'Use Custom' to have translated labels

**Screenshots or video**
![Screenshot 2024-01-19 092636](https://github.com/raspberrypi/rpi-imager/assets/146750643/8394748c-d325-407f-9815-ebaeb1aa9d03)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma, Windows, Raspberry Pi OS

**Additional context**
This only appears to affect strings using the tr() macro in the C++ side of the codebase. The QML side translates dynamically as expected.

**Comment by lurch** [comment]
Do you get the same problem when RPi Imager is **started** in a non-English language, or only when dynamically changing the language when it's already running? (I don't have any insight to offer, but that might help track down which part of the process is going wrong?)

**Comment by maxnet** [comment]
>This only appears to affect strings using the tr() macro 

Macro?!
We are not some GLib (or VBA ;-) ) application....


Qt is a proper Object Orientated framework.
Class methods everywhere.
tr() is a class method that ImageWriter has inherited from QObject.

QObject::tr() looks inside the .ts/.qm translation file for strings under the context of the class name.
I do not see you providing a translation for the string "Erase" under the context "ImageWriter": https://github.com/raspberrypi/rpi-imager/blob/qml/src/i18n/rpi-imager_nl.ts#L254-L279
There do is one under the context "main", but it will not go looking under there...



Also keep in mind that because Qt uses class methods of QObject everywhere, certain constructs such as your static methods inside a namespace kung fu are not so good to have inside a Qt application.
If you wanted to use tr() there, you would not be able to...

**Comment by tdewey-rpi** [comment]
> > This only appears to affect strings using the tr() macro
> 
> Macro?! We are not some GLib (or VBA ;-) ) application....
> 
> Qt is a proper Object Oriented C++ framework. tr() is an instance method that our ImageWriter class has inherited from QObject.
> 
> QObject::tr() looks inside the .ts/.qm translation file for strings under the context of the class name. I do not see you providing a translation for the string "Erase" under the context "ImageWriter": https://github.com/raspberrypi/rpi-imager/blob/qml/src/i18n/rpi-imager_nl.ts#L254-L279 There do is one under the context "main", but it will not go looking under there...
> 
> Also keep in mind that because Qt uses instance methods everywhere, certain constructs such as your loose methods inside a namespace are not so good to have inside a Qt application. If at some point you wanted to use tr() there, you would not be able to...

Oddly enough, I expected that - but I didn't get what I expected when I provided the context "main", where the translations currently are. Instead I got empty labels.

Entirely possible I was using the wrong translation object - so I'll take another look with some regenerated translation files.

**Comment by tdewey-rpi** [comment]
A delightful little bug:

1) I was using the wrong translation object. You can't specify a context via tr(), which means using it at all is effectively an antipattern. I'll be changing references to tr() to statically locate strings in the future to avoid this sort of thing going forward.
2) Regenerating the translation files identified the move - but didn't create a new context. Poor behaviour from the Qt tooling, with tr() still broken.
3) Forcing the use of QCoreApplication::translate, as recommended on the Qt website, allows you to specify a context - resolving part 1 of the bug.
4) The language replacement, however, races with the OS list assembly. So I've added an additional osListPrepared signal emission when we replace the translator. Translations now act as expected.
