### ISSUE TITLE
[BUG]: "customisation" is spelled incorrectly in the app on MacOS. OS Customisation screen should be "OS Customization" screen.

### ISSUE THREAD

**Issue by Danrancan** [raspberrypi/rpi-imager#864]
### What happened?

I am running Imager on MacOS.
There are 3 different places where "customization" is spelled incorrectly as "customisation" on the app.

1) The first place it is misspelled is in the advanced configuration window that pops up when pressing "Command+Shift+x". The advanced configuration window is entitled "OS Customisation". It should be "OS Customization".

2) The second place it is misspelled is after pressing the "NEXT" button on the main screen. A popup menu appears entitled "Use OS customisation?". It should read "Use OS Customization?".

3) The third place it is misspelled is on the same pop-up menu as the last, below the title, it reads "Would you like to apply OS customisation settings?". It should instead read "Would you like to apply OS customization settings?".

Note: This very bug report also misspells "customisation" under the "OS Customisation" Heading, and also in the sentance below that which reads "Were you using OS Customisation when you encountered the bug?". It should read "OS Customization" for the heading, and below read "Were you using OS Customization when you encountered the bug?"

Seems like someone is having a hard time spelling customization correctly.

Please fix these spelling errors when you get a chance.

### Version

1.8.5 (Default)

### What host operating system were you using?

macOS

### Host OS Version

Sonoma 14.4.1

### Selected OS

Ubuntu Server 22.04

### Which Raspberry Pi Device are you using?

Raspberry Pi 4B, 400, and Compute Modules 4, 4S

### What kind of storage device are you using?

USB Pen Drive

### OS Customisation

- [X] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment]
Thanks for the report, @Danrancan

This is not an error.

To add some colour: the application, when rendering in English, presents in en-GB. This is both by design and consistent with other Raspberry Pi applications and web properties.

I'm happy to review a PR offering an en-US translation, of course. This PR would have to strictly only apply to en-US locales, and I would expect the translator to provide best-effort maintenance of all strings going forward (as we currently get from our excellent non-English community translators today).
