### ISSUE TITLE
Application can't be tracked by MacUpdater

### ISSUE THREAD

**Issue by ulfklose** [raspberrypi/rpi-imager#88]
I got in contact with the creators of MacUpdater and asked them why the rpi-imager isn't being tracked by their application.

The possible reason is explained here: https://www.corecode.io/macupdater/faq.html#SHOWUP

I don't know of this is of any relevance for you guys but I'd like to ask you, if possible, to fix this.

**Comment by maxnet** [comment]
>The possible reason is explained here: https://www.corecode.io/macupdater/faq.html#SHOWUP

"If you want to find out why a particular app does not show up in MacUpdater, you can drag the app onto MacUpdater's main window to get an explanation."
So what does that give for you?

**Comment by ulfklose** [comment]
Sorry, my bad, I could have done this right on creating this ticket.

<img width="547" alt="Bildschirmfoto 2020-07-05 um 14 25 37" src="https://user-images.githubusercontent.com/47573/86532588-83f91880-becb-11ea-9120-bd20b2d5ff88.png">

**Comment by core-code** [comment]
this means both the CFBundleVersion and CFBundleShortVersionString entries in the Info.plist are missing.

this is not just a problem with regards to MacUpdater but:

• not having a version number is a violation of Apple's macOS development guidelines
• if you have multiple versions installed, macOS will be unable to determine which version is the newest one
• also if you select the app in the Finder (via Get Info, Column View or Quick Look) you will not be able to inspet the version number (because it is missing). Mac users are accustomed to be able to inspect the version numbers of any app in the Finder.

**Comment by maxnet** [comment]
Thanks for the info.
Will populate those in the .plist.

**Comment by core-code** [comment]
thanks i can confirm that the 1.4 release here:
https://github.com/raspberrypi/rpi-imager/releases/download/v1.4/imager.dmg

fixes the issue. however the download from the homepage ( https://www.raspberrypi.org/downloads/ ) doesn't seem to be updated yet.

**Comment by maxnet** [comment]
>thanks i can confirm that the 1.4 release here:
>fixes the issue

Good to hear.

>however the download from the homepage ( https://www.raspberrypi.org/downloads/ ) doesn't seem to be updated yet.

Has been updated now.
Can be a slight delay due to different people in charge of the github page (where releases are basically only created so that the code in the repository is tagged correctly), downloads.raspberrypi.org and www.raspberrypi.org
