### ISSUE TITLE
[FEATURE]: wifi language quick access in dropdown lists

### ISSUE THREAD

**Issue by DirectXNinja** [raspberrypi/rpi-imager#937]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you would like to see implemented

rpi-imager should have a atleast a scrollbar on the side for wifi country, and preferbly also quick access hotkeys in dropdown list (press u and jump to u section). Would also be great if we could get a dropdown menu for things like checking for update etc.
(windows rpi-imager 1.8.5)

### Describe alternatives you've considered

nothing

### Additional context

nothing

### Version

1.8.5

**Comment by tdewey-rpi** [comment]
Thanks for the report, @DirectXNinja.

I'm marking this one as 'Fixed', because it's fixed as far as is practical while using the Qt controls we're using in the v1.9.0 release, available from the Releases area.

In practice, the quick access is available, but the scrollbar is still unavailable. You can, however, achieve a faster scroll by using your mouse pointer like a touch device - grab a list item, and 'fling' it.
